# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Kind(StrEnum):
    registration = "registration"
    deployment_confirmation = "deployment_confirmation"
    baseline_observation = "baseline_observation"
    treatment_observation = "treatment_observation"
    control_observation = "control_observation"
    raw_observation_ref = "raw_observation_ref"
    did_inputs = "did_inputs"
    did_outputs = "did_outputs"
    b_gate_decision = "b_gate_decision"
    grs_policy = "grs_policy"
    missingness_report = "missingness_report"
    remediation = "remediation"
    rollback = "rollback"


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class Entry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    content_hash: Sha256Ref
    ref: UriRef


class EvidenceBundleManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entries: Annotated[list[Entry], Field(min_length=1)]
    manifest_hash: Sha256Ref
    created_at: TimestampUtc
