# GENERATED by tools/validation codegen recipe (justfile codegen) - DO NOT EDIT
"""saena_schemas -- codegen-only typed contract models (ADR-0011 SSOT split).

Do not hand-edit anything under this package except pyproject.toml and
py.typed (packaging scaffolding exception, packages/schemas/README.md).
Every module here, including this file, is regenerated by the codegen
justfile recipe from packages/contracts -- see
tools/validation/codegen-patch-openroot.py.
"""

__version__ = "0.1.0"
