"""saena_schemas — codegen-only typed contract models (ADR-0011 SSOT split).

Do not hand-edit anything under this package except this file and py.typed
(packaging scaffolding exception, packages/schemas/README.md). Every other
module here is regenerated by `just codegen` from packages/contracts — see
tools/validation/codegen-patch-openroot.py and the `codegen` justfile recipe.
"""

__version__ = "0.1.0"
