# SAENA RAPID-7 task runner (ADR-0010). `just verify` == the CI gate set;
# keep the two in lockstep (drift violates ADR-0018).
# just is provided by the dev group (rust-just, pinned in uv.lock):
#   uv run just <recipe>   — no host-global install required.

set shell := ["sh", "-c"]

default:
    @just --list

# One-time / after dependency changes
setup:
    uv sync --locked

lint:
    uv run ruff check .
    uv run ruff format --check .

typecheck:
    uv run mypy

test:
    uv run pytest -q

# Module boundary contracts (dependency-policy rule 11 / ADR-0002)
boundaries:
    uv run lint-imports

# Validate all contract schemas. Honest when empty: reports the count.
contracts-validate:
    @count=$(find packages/contracts -name '*.schema.json' 2>/dev/null | wc -l | tr -d ' '); \
    if [ "$count" = "0" ]; then \
        echo "contracts-validate: no *.schema.json under packages/contracts yet (W1 delivers schemas) — nothing validated"; \
    else \
        find packages/contracts -name '*.schema.json' -print0 | xargs -0 uv run check-jsonschema --check-metaschema; \
    fi

# Codegen pipeline (w1-12, ADR-0011 SSOT split): packages/contracts (hand-edited
# JSON Schema SSOT) -> packages/schemas/saena_schemas (codegen-only pydantic v2
# models). Flag set is BINDING per CODEGEN_LOSSLESS gate verdict (Lead,
# 2026-07-12) — do not change the flags below without re-running the gate,
# WITH ONE PROVEN EXCEPTION recorded here: the gate verdict mandated
# `--type-mappings "string+date-time=string"` for format:date-time + pattern
# collisions (TypeError at validation time) but did not anticipate the
# identical failure mode for format:uuid + pattern (event-envelope's
# event_id: format uuid + a UUIDv7 pattern) — the gate's own lossless test
# (packages/schemas/tests/test_lossless.py::test_envelope_valid_fixtures_parse)
# caught this as a real TypeError parsing the ADR-0013 fixtures, so
# `string+uuid=string` was added by the same proven mechanism, narrowly
# scoped to the one additional format that collides with `pattern` in this
# contract set. Glob-driven: any new category/contract dropped under
# packages/contracts/json-schema/** is picked up automatically on the next
# run, no recipe edit required.
#
# Open-contract list ($comment: sourced from the approved plan §5 acceptance
# matrix; hardcoded here only until packages/contracts/registry.json carries a
# compat_class field per contract, w1-15 — registry.json becomes the source of
# truth at that point and this list should be replaced with a read from it).
codegen:
    #!/bin/sh
    set -eu
    OPEN_CONTRACTS="context/workspace_context_v1 context/project_context_v1 context/site_context_v1 context/run_context_lifecycle_v1 domain/verification_result_v1 event/patch_unit_completed_v1 event/quality_gate_result_v1 event/plan_contract_proposed_v1 event/plan_contract_approved_v1 event/repo_intaken_v1 event/site_inventory_completed_v1"
    PKG_ROOT=packages/schemas/saena_schemas
    rm -rf "$PKG_ROOT"/context "$PKG_ROOT"/domain "$PKG_ROOT"/event "$PKG_ROOT"/envelope "$PKG_ROOT"/common
    for schema in packages/contracts/json-schema/*/*/v*/*.schema.json; do
        [ -e "$schema" ] || continue
        category=$(echo "$schema" | cut -d/ -f4)
        name=$(echo "$schema" | cut -d/ -f5)
        major=$(echo "$schema" | cut -d/ -f6)
        module_name=$(echo "$name" | tr '-' '_')_${major}
        out_dir="$PKG_ROOT/$category/$module_name"
        mkdir -p "$PKG_ROOT/$category"
        rm -rf "$out_dir"
        uv run datamodel-codegen \
            --input "$schema" \
            --input-file-type jsonschema \
            --output-model-type pydantic_v2.BaseModel \
            --target-python-version 3.12 \
            --schema-version 2020-12 \
            --use-annotated \
            --allow-remote-refs \
            --type-mappings "string+date-time=string" "string+uuid=string" \
            --custom-file-header "# GENERATED by datamodel-code-generator — DO NOT EDIT" \
            --output "$out_dir"
        # Normalize: dmcg writes a single FILE (not a package dir) when the
        # contract has no cross-file $ref that needs its own submodule. Wrap
        # it into <name>_vN/__init__.py so every contract is a uniform module.
        if [ -f "$out_dir" ]; then
            tmp="${out_dir}.tmp_pkg"
            mkdir -p "$tmp"
            mv "$out_dir" "$tmp/__init__.py"
            mv "$tmp" "$out_dir"
        fi
        touch "$PKG_ROOT/$category/__init__.py"
    done
    OPEN_ARGS=""
    for c in $OPEN_CONTRACTS; do
        OPEN_ARGS="$OPEN_ARGS --open $c"
    done
    uv run python3 tools/validation/codegen-patch-openroot.py "$PKG_ROOT" $OPEN_ARGS
    uv run ruff format "$PKG_ROOT"
    uv run ruff check --fix "$PKG_ROOT"

# Drift gate (ADR-0018): regenerate and fail if committed packages/schemas
# output differs from a fresh codegen run.
codegen-check: codegen
    git diff --exit-code -- packages/schemas

# Local gate — mirrors CI (ADR-0018)
verify: lint typecheck test boundaries contracts-validate
    @echo "verify: all local gates green"

# Worktree lifecycle (ADR-0023)
worktree-create unit +args:
    sh tools/development/worktree.sh create {{unit}} {{args}}

worktree-destroy unit:
    sh tools/development/worktree.sh destroy {{unit}}

worktree-audit:
    sh tools/development/worktree.sh audit

# Tier-2 local profile (defined W0, used from W2A — ADR-0022)
dev-up +services:
    @test -f tools/development/docker-compose.dev.yaml || { echo "dev-up: tools/development/docker-compose.dev.yaml not present yet (T15/W2A)"; exit 1; }
    docker compose -f tools/development/docker-compose.dev.yaml up -d {{services}}
