# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import engine_id as engine_id_1


class CommonFields(RootModel[Any]):
    root: Any


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class DeIdentificationStatus(StrEnum):
    k_anonymized = "k_anonymized"
    suppressed = "suppressed"
    pending_review = "pending_review"


class EventId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="UUIDv7, sortable event identifier. Version nibble fixed to 7, variant nibble in {8,9,a,b} per RFC 9562.",
            pattern="^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
        ),
    ]


class EventType(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="9th field (ADR-0013 deviation from k3s §4.1 8-field list). Identical to AsyncAPI topic name.",
            pattern="^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*){2,3}\\.v[0-9]+$",
        ),
    ]


class IdempotencyKey(RootModel[str]):
    root: Annotated[str, Field(description="Dedup key under at-least-once delivery.", min_length=1)]


class OccurredAt(RootModel[TimestampUtc]):
    root: TimestampUtc


class EngineRequiredPayload(BaseModel):
    engine_id: engine_id_1.Schema


class Producer(RootModel[str]):
    root: Annotated[str, Field(description="Publishing service identifier.", min_length=1)]


class SchemaVersion(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="semver contract version (ADR-0012 compatibility policy target).",
            pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$",
        ),
    ]


class TraceId(RootModel[str]):
    root: Annotated[
        str,
        Field(description="W3C trace context format, 32-hex.", pattern="^[0-9a-f]{32}$"),
    ]


class Payload(BaseModel):
    engine_id: Annotated[
        engine_id_1.Schema | None,
        Field(
            description="Closed enum, v1 single value (ADR-0013). Required for observation/citation/experiment event families; present here as an optional property so non-engine events remain valid. Any value outside the enum (e.g. Google/Gemini) is rejected at the schema level (CLAUDE.md Engine scope v1)."
        ),
    ] = None


class TenantContextEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: EventId
    context_type: Literal["tenant"]
    tenant_id: Annotated[
        TenantId,
        Field(description="Required for tenant context (ADR-0013, ADR-0014 slug format)."),
    ]
    run_id: Annotated[
        RunId,
        Field(
            description="Required for tenant context (ADR-0013 rev.2 ④ — Open decisions item 1 closed: tenant branch run_id stays required, not nullable)."
        ),
    ]
    schema_version: SchemaVersion
    producer: Producer
    occurred_at: OccurredAt
    trace_id: TraceId
    idempotency_key: IdempotencyKey
    event_type: EventType
    payload: Payload


class SystemContextEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: EventId
    context_type: Literal["system"]
    schema_version: SchemaVersion
    producer: Producer
    occurred_at: OccurredAt
    trace_id: TraceId
    idempotency_key: IdempotencyKey
    event_type: EventType
    payload: Payload


class AggregateContextEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: EventId
    context_type: Literal["aggregate"]
    schema_version: SchemaVersion
    producer: Producer
    occurred_at: OccurredAt
    trace_id: TraceId
    idempotency_key: IdempotencyKey
    event_type: EventType
    aggregate_scope_id: Annotated[str, Field(min_length=1)]
    cohort_size: Annotated[int, Field(ge=1)]
    privacy_threshold: Annotated[int, Field(ge=1)]
    de_identification_status: DeIdentificationStatus
    lineage_audit_ref: Annotated[
        str,
        Field(
            description="Opaque audit-ledger hash reference. Audit-role-only viewing at the application layer; schema cannot enforce access control.",
            min_length=1,
        ),
    ]
    payload: Payload


class SaenaEventEnvelopeV1(
    RootModel[TenantContextEnvelope | SystemContextEnvelope | AggregateContextEnvelope]
):
    root: Annotated[
        TenantContextEnvelope | SystemContextEnvelope | AggregateContextEnvelope,
        Field(
            description="Implements ADR-0013 event envelope v1 (9 common fields + context_type discriminator: tenant | system | aggregate) and ADR-0013 rev.2 (payload as 10th structural member, required in all branches; occurred_at Z-canonical; schema_version prerelease/build excluded; tenant branch run_id required).",
            title="SAENA event envelope v1",
        ),
    ]
