# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import engine_id as engine_id_1


class PredictedLayer(StrEnum):
    discovery = "discovery"
    citation = "citation"
    absorption = "absorption"
    prominence = "prominence"
    referral = "referral"


class Risk(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"


class Hypothes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(min_length=1)]
    query_cluster_ids: Annotated[list[str], Field(min_length=1)]
    evidence_ids: Annotated[list[str], Field(min_length=1)]
    predicted_layers: Annotated[list[PredictedLayer], Field(min_length=1)]
    expected_effect_distribution: Annotated[dict[str, float], Field(min_length=1)]
    risk: Risk


class PatchUnit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(min_length=1)]
    files: Annotated[list[str], Field(min_length=1)]
    allowed_transformations: Annotated[list[str], Field(min_length=1)]
    tests: Annotated[list[str], Field(min_length=1)]
    rollback: Annotated[str, Field(min_length=1)]


class ScopeLimits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_globs: Annotated[int, Field(ge=1)]


class DiffBudget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_files: Annotated[int, Field(ge=1)]
    max_lines: Annotated[int, Field(ge=1)]


class RejectedAlternative(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class EngineRequiredPayload(BaseModel):
    engine_id: engine_id_1.Schema


class ChangeplanActionContract(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    run_id: RunId
    tenant_id: TenantId
    repo_commit: GitSha
    approved_scope: Annotated[list[str], Field(min_length=1)]
    engine_scope: Annotated[list[engine_id_1.Schema], Field(min_length=1)]
    hypotheses: Annotated[list[Hypothes], Field(min_length=1)]
    patch_units: Annotated[list[PatchUnit], Field(min_length=1)]
    approval_required: Literal[True]
    no_deploy: Literal[True]
    no_push: Literal[True]
    evidence_ledger_hash: Sha256Ref
    scope_limits: ScopeLimits
    diff_budget: DiffBudget
    rejected_alternatives: Annotated[list[RejectedAlternative], Field(min_length=0)]
