# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class EntityType(StrEnum):
    brand = "brand"
    product = "product"
    integration = "integration"
    competitor = "competitor"


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class EntityRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tenant_id: TenantId
    project_id: ProjectId
    entity_id: Annotated[str, Field(max_length=128, min_length=1)]
    graph_version: Annotated[str, Field(min_length=1)]
    entity_type: EntityType
    canonical_name: Annotated[str, Field(max_length=256, min_length=1)]
    updated_at: TimestampUtc
