# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error_code: Annotated[str, Field(pattern="^saena\\.[a-z_]+\\.[a-z_]+$")]
    retryable: bool
    summary: Annotated[str, Field(max_length=500, min_length=1)]
