# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel


class EngineId(StrEnum):
    chatgpt_search = "chatgpt-search"


class EngineRequiredPayload(BaseModel):
    engine_id: EngineId
