# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import engine_id as engine_id_1


class IsolationProfile(StrEnum):
    internal_k3s = "internal-k3s"
    saas_shared = "saas-shared"


class Status(StrEnum):
    active = "active"
    suspended = "suspended"
    terminating = "terminating"


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class EngineRequiredPayload(BaseModel):
    engine_id: engine_id_1.Schema


class TenantContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tenant_id: TenantId
    display_name: Annotated[str, Field(min_length=1)]
    isolation_profile: IsolationProfile
    namespace: Annotated[str, Field(pattern="^saena-tenant-[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]
    policy_version: Semver
    engine_scope: Annotated[list[engine_id_1.Schema], Field(min_length=1)]
    status: Status
    retention_policy_ref: Annotated[str, Field(min_length=1)]
    created_at: TimestampUtc
    updated_at: TimestampUtc
