#!/usr/bin/env python3
"""Deterministic post-codegen patch: mark OPEN-class contract root models extra='allow'.

Authority: CODEGEN_LOSSLESS gate verdict (Lead, 2026-07-12 — BINDING mechanism A).

Mechanism A: `datamodel-code-generator` is run with default inference (no blanket
`--allow-extra-fields`), so every generated model gets `extra='forbid'` (from
`additionalProperties: false` / `unevaluatedProperties: false`) or is left open
(no `model_config`, or an auto-generated `extra='allow'` when the source schema
declares `additionalProperties: true`) purely from the source schema's own
closedness signal. This script is the second, deterministic step: for the
OPEN-class contract set only, it inserts `model_config = ConfigDict(extra='allow')`
into the contract's ROOT model when that model has no `model_config` at all.

The OPEN-class set is NOT auto-discovered from the generated code (that would
defeat the purpose of a tripwire). It is passed in explicitly by the caller
(the `codegen` justfile recipe), sourced from the approved plan §5 acceptance
matrix. Until packages/contracts/registry.json exists with a `compat_class`
field per contract (w1-15), the open-contract list is hardcoded in the caller
with a $comment pointing at registry.json as the future source of truth.

Root model identification: NOT based on class-definition order or a title ->
class-name string transform (both are guesswork that can silently pick the
wrong class, e.g. when a $defs-only auxiliary object happens to be emitted
after the schema's real root — observed empirically with common/engine-id's
`engine_required_payload` $defs entry). Instead, for each contract this script
reads the ORIGINAL JSON Schema's own top-level `properties` keys and finds the
generated `BaseModel` subclass whose field names are exactly that set. This is
the only condition that cannot mismatch: the root model is defined, by
construction, as "the class with these exact fields," independent of codegen's
internal class-ordering or naming heuristics. Schemas with no top-level
`type: object` + `properties` (bare enums, $defs-only reuse files) have no
object root at all and are skipped — they carry no extra='allow'/'forbid'
concept to patch or tripwire-check.

Safety tripwire: for any CLOSED contract (i.e. not in the open-contract list)
whose root model is found this way, this script verifies the root model
already carries `model_config = ConfigDict(extra='forbid')`. If it does not,
the script exits 1 rather than silently leaving an unsealed closed contract —
a poisoned or misconfigured codegen run must fail loudly, not degrade contract
sealing.

Idempotent: re-running against an already-patched tree is a no-op (byte-for-byte
identical output) because the insertion is a no-op when `model_config` is
already present with `extra='allow'`.
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from dataclasses import dataclass
from pathlib import Path

GENERATED_HEADER_PREFIX = "# GENERATED by datamodel-code-generator"

MODEL_CONFIG_ALLOW_BLOCK = "    model_config = ConfigDict(\n        extra='allow',\n    )\n"


@dataclass(frozen=True)
class RootModelInfo:
    module_path: Path
    class_name: str
    class_lineno: int  # 1-indexed, line of the `class X(...):` statement
    has_model_config: bool
    model_config_extra_value: str | None


class TripwireError(RuntimeError):
    """Raised when a CLOSED contract's root model is not sealed as expected."""


def _schema_root_property_names(schema_path: Path) -> frozenset[str] | None:
    """Top-level `properties` keys of the ORIGINAL JSON Schema, or None if the
    schema has no `type: object` root with declared properties (bare enum,
    $defs-only reuse file — no object root to patch/tripwire-check).
    """
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    if schema.get("type") != "object" or "properties" not in schema:
        return None
    return frozenset(schema["properties"].keys())


def _class_field_names(class_node: ast.ClassDef) -> frozenset[str]:
    names = set()
    for stmt in class_node.body:
        if (
            isinstance(stmt, ast.AnnAssign)
            and isinstance(stmt.target, ast.Name)
            and stmt.target.id != "model_config"
        ):
            names.add(stmt.target.id)
    return frozenset(names)


def _find_root_model_by_fields(
    module_path: Path, expected_fields: frozenset[str]
) -> RootModelInfo | None:
    """Find the top-level `class X(BaseModel):` whose annotated field names
    are exactly `expected_fields`. Returns None if no such class exists.
    """
    source = module_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(module_path))

    candidates = [
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and _class_field_names(node) == expected_fields
    ]
    if not candidates:
        return None
    if len(candidates) > 1:
        raise TripwireError(
            f"{module_path}: {len(candidates)} generated classes all match the "
            f"schema's root property set {sorted(expected_fields)} "
            f"({[c.name for c in candidates]}) — ambiguous root, refusing to guess"
        )
    root = candidates[0]

    has_model_config = False
    extra_value: str | None = None
    for stmt in root.body:
        assign_stmt: ast.Assign | ast.AnnAssign | None = None
        target_names: list[str] = []
        if isinstance(stmt, ast.Assign):
            assign_stmt = stmt
            target_names = [t.id for t in stmt.targets if isinstance(t, ast.Name)]
        elif isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            assign_stmt = stmt
            target_names = [stmt.target.id]
        if assign_stmt is not None and "model_config" in target_names:
            has_model_config = True
            extra_value = _extract_extra_value(assign_stmt)

    return RootModelInfo(
        module_path=module_path,
        class_name=root.name,
        class_lineno=root.lineno,
        has_model_config=has_model_config,
        model_config_extra_value=extra_value,
    )


def _extract_extra_value(stmt: ast.Assign | ast.AnnAssign) -> str | None:
    value = stmt.value
    if not isinstance(value, ast.Call):
        return None
    for kw in value.keywords:
        if kw.arg == "extra" and isinstance(kw.value, ast.Constant):
            return str(kw.value.value)
    return None


def _insert_extra_allow(info: RootModelInfo) -> None:
    """Insert `model_config = ConfigDict(extra='allow')` as the first statement
    in the root model's body. Also ensures `ConfigDict` is imported from pydantic.
    """
    lines = info.module_path.read_text(encoding="utf-8").splitlines(keepends=True)

    class_line_idx = info.class_lineno - 1
    insert_idx = class_line_idx + 1
    # Skip a docstring, if the root model has one, so model_config lands
    # directly after it (cosmetic, but keeps generated-code shape conventional).
    body_source = "".join(lines[insert_idx:])
    stripped = body_source.lstrip()
    if stripped.startswith(('"""', "'''")):
        quote = stripped[:3]
        end = stripped.find(quote, 3)
        if end != -1:
            docstring_text = stripped[: end + 3]
            consumed = body_source[: body_source.index(docstring_text) + len(docstring_text)]
            consumed_lines = consumed.count("\n") + (0 if consumed.endswith("\n") else 1)
            insert_idx += consumed_lines

    lines.insert(insert_idx, MODEL_CONFIG_ALLOW_BLOCK)
    new_source = "".join(lines)
    new_source = _ensure_configdict_import(new_source)
    info.module_path.write_text(new_source, encoding="utf-8")


def _ensure_configdict_import(source: str) -> str:
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == "pydantic":
            names = {alias.name for alias in node.names}
            if "ConfigDict" in names:
                return source
            # Rewrite the import line to add ConfigDict, alphabetically sorted
            # to match the repo's ruff `I` (isort) convention.
            all_names = sorted(names | {"ConfigDict"})
            old_import_src = ast.get_source_segment(source, node)
            assert old_import_src is not None
            new_import_src = f"from pydantic import {', '.join(all_names)}"
            return source.replace(old_import_src, new_import_src, 1)
    raise TripwireError(
        "expected a top-level 'from pydantic import ...' statement to patch "
        "with ConfigDict, found none"
    )


def _discover_contracts(package_dir: Path, contracts_root: Path) -> list[tuple[Path, Path]]:
    """Pair each generated `<category>/<name>_v<major>/__init__.py` contract
    root module with its original source schema under `contracts_root`
    (packages/contracts/json-schema), by directory-name convention:
    saena_schemas/<category>/<name_snake>_v<major>/  <->
    packages/contracts/json-schema/<category>/<name-kebab>/v<major>/*.schema.json
    """
    pairs = []
    for init_path in sorted(package_dir.glob("*/*/__init__.py")):
        category = init_path.parent.parent.name
        module_dir_name = init_path.parent.name  # e.g. tenant_context_v1
        *name_parts, major = module_dir_name.rsplit("_", 1)
        name_snake = "_".join(name_parts)
        name_kebab = name_snake.replace("_", "-")
        schema_dir = contracts_root / category / name_kebab / major
        matches = list(schema_dir.glob("*.schema.json")) if schema_dir.is_dir() else []
        if len(matches) != 1:
            raise TripwireError(
                f"{init_path}: could not uniquely resolve source schema under "
                f"{schema_dir} (found {len(matches)} candidates) — "
                f"directory-naming convention mismatch"
            )
        pairs.append((init_path, matches[0]))
    return pairs


def patch_open_roots(
    package_dir: Path,
    contracts_root: Path,
    open_contract_dirs: list[str],
) -> list[str]:
    """Walk every `<category>/<name>_v<major>/__init__.py` contract root module
    under `package_dir`, patch OPEN-class roots, and tripwire-check CLOSED ones.

    `open_contract_dirs` entries are `<category>/<name>_v<major>` relative paths
    (e.g. `context/workspace_context_v1`).

    Returns the list of module paths (relative to package_dir) that were
    actually modified (for reporting — empty on a fully-idempotent re-run).
    """
    open_set = set(open_contract_dirs)
    changed: list[str] = []

    contract_pairs = _discover_contracts(package_dir, contracts_root)
    for init_path, schema_path in contract_pairs:
        contract_rel = str(init_path.parent.relative_to(package_dir))
        expected_fields = _schema_root_property_names(schema_path)
        if expected_fields is None:
            continue  # bare enum / $defs-only reuse file — no object root

        info = _find_root_model_by_fields(init_path, expected_fields)
        if info is None:
            raise TripwireError(
                f"{contract_rel}: schema declares an object root with fields "
                f"{sorted(expected_fields)} but no generated class matches — "
                f"codegen output does not match its source schema"
            )

        is_open = contract_rel in open_set

        if is_open:
            if info.has_model_config and info.model_config_extra_value == "allow":
                continue  # already patched (or auto-generated as open) — idempotent
            if info.has_model_config:
                raise TripwireError(
                    f"{contract_rel}: OPEN-class root '{info.class_name}' has an "
                    f"unexpected model_config (extra={info.model_config_extra_value!r}), "
                    f"refusing to override — investigate before re-running"
                )
            _insert_extra_allow(info)
            changed.append(str(init_path.relative_to(package_dir)))
        else:
            if not (info.has_model_config and info.model_config_extra_value == "forbid"):
                raise TripwireError(
                    f"{contract_rel}: CLOSED-class root '{info.class_name}' does NOT "
                    f"carry model_config=ConfigDict(extra='forbid') after codegen "
                    f"(found extra={info.model_config_extra_value!r}, "
                    f"has_model_config={info.has_model_config}). This is the safety "
                    f"tripwire — a closed contract must never be silently left "
                    f"unsealed. Refusing to continue."
                )

    found_dirs = {str(p.parent.relative_to(package_dir)) for p, _ in contract_pairs}
    missing_open = open_set - found_dirs
    if missing_open:
        print(
            "codegen-patch-openroot: note — open-contract entries not found in "
            f"generated tree (schema not yet present in this worktree): "
            f"{sorted(missing_open)}",
            file=sys.stderr,
        )

    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "package_dir",
        type=Path,
        help="Generated package root (e.g. packages/schemas/saena_schemas)",
    )
    parser.add_argument(
        "--contracts-root",
        type=Path,
        default=Path("packages/contracts/json-schema"),
        help="Original JSON Schema SSOT root (default: packages/contracts/json-schema)",
    )
    parser.add_argument(
        "--open",
        dest="open_contract_dirs",
        action="append",
        default=[],
        metavar="CATEGORY/NAME_vN",
        help="Open-class contract module path, relative to package_dir "
        "(repeatable, e.g. --open context/workspace_context_v1)",
    )
    args = parser.parse_args(argv)

    package_dir: Path = args.package_dir
    if not package_dir.is_dir():
        parser.error(f"package_dir does not exist or is not a directory: {package_dir}")
    contracts_root: Path = args.contracts_root
    if not contracts_root.is_dir():
        parser.error(f"--contracts-root does not exist or is not a directory: {contracts_root}")

    try:
        changed = patch_open_roots(package_dir, contracts_root, args.open_contract_dirs)
    except TripwireError as exc:
        print(f"codegen-patch-openroot: TRIPWIRE — {exc}", file=sys.stderr)
        return 1

    if changed:
        print("codegen-patch-openroot: patched open-class roots:")
        for rel in changed:
            print(f"  {rel}")
    else:
        print("codegen-patch-openroot: no changes (idempotent — all roots already correct)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
