# GENERATED by datamodel-code-generator — DO NOT EDIT

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DeploymentTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[str, Field(min_length=1)]
    identifier: Annotated[str, Field(min_length=1)]


class Sha256Ref(RootModel[str]):
    root: Annotated[str, Field(pattern="^sha256:[0-9a-f]{64}$")]


class TenantId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$")]


class WorkspaceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ProjectId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SiteId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class ActorId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class RunId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class Semver(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")]


class TimestampUtc(RootModel[str]):
    root: Annotated[
        str,
        Field(pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z$"),
    ]


class GitSha(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{40}$")]


class UriRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9+.-]+://[^?#]+$")]


class RegistrationRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    experiment_id: Annotated[str, Field(max_length=128, min_length=1)]
    registration_canonical_hash: Sha256Ref


class Confirmer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identity: Annotated[str, Field(min_length=1)]
    method: Annotated[str, Field(min_length=1)]
    signature_ref: UriRef | None = None


class DeploymentConfirmedV1Payload(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    deployment_id: Annotated[str, Field(max_length=128, min_length=1)]
    registration_ref: RegistrationRef
    deployed_commit_sha: GitSha | None = None
    artifact_hash: Sha256Ref | None = None
    deployment_target: DeploymentTarget
    confirmer: Confirmer
    confirmed_at: TimestampUtc
